**THEORETICAL QUESTIONS**

1.. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it
enhance Python's capabilities for numerical operations?

ANSWER: Purpose and Advantages of NumPy in Scientific Computing and Data Analysis
Purpose:
NumPy is a fundamental package for numerical computing in Python. It provides support for large, multi-dimensional arrays and matrices, along with a collection of high-performance mathematical functions to operate on them.

Advantages:

*Efficiency: NumPy operations are implemented in C, making them much faster than native Python loops.

*Array-Oriented Computing: Efficient handling of large data arrays without explicit looping.

*Broadcasting and Vectorization: Allows element-wise operations without writing loops.

*Integration: Works well with other scientific libraries (e.g., SciPy, pandas, matplotlib).

*Memory Efficiency: Uses less memory than Python lists for large data.



2.Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the
other?

ANSWER : np.mean() vs np.average()
*np.mean(): Computes the arithmetic mean along the specified axis. It treats all values equally.

*np.average(): Also computes the mean, but allows weights to be specified.

When to use:

*Use np.mean() when each element contributes equally.

*Use np.average() when some elements should contribute more (weighted average).


3.Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D
arrays.

ANSWER :  Reversing a NumPy Array Along Axes
  
  *1D Array:

In [2]:
import numpy as np
a = np.array([1, 2, 3])
a[::-1]

array([3, 2, 1])

* 2D array:


In [3]:
b = np.array([[1, 2], [3, 4]])
b[::-1]      # Reverses rows
b[:, ::-1]   # Reverses columns
b[::-1, ::-1]

array([[4, 3],
       [2, 1]])

4.How can you determine the data type of elements in a NumPy array? Discuss the importance of data types
in memory management and performance.

ANSWER : Determining Data Type and Its Importance

Method:

In [4]:
arr = np.array([1, 2, 3])
print(arr.dtype)

int64


Importance:

*Memory Management: NumPy arrays use fixed, uniform data types for memory efficiency.

*Performance: Operations are optimized for specific data types (e.g., float32 vs float64).

*Compatibility: Ensures data consistency when passing between functions or libraries.




5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

ANSWER : Defining ndarray and Its Key Features
*ndarray: The core data structure in NumPy, representing an n-dimensional array.

Key Features:

*Fixed size, homogeneous data types.

*Efficient memory layout.

*Supports vectorized operations.

*Built-in broadcasting.

Difference from Lists:

*Lists are heterogeneous, dynamic, and slower for numerical computations.

*ndarray enables element-wise operations without loops.

6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

ANSWER :  Performance Benefits of NumPy Arrays Over Python Lists
Speed: NumPy uses compiled C code under the hood.

Vectorization: Eliminates Python loops, improving speed.

Memory: Contiguous memory layout vs. pointers in lists.

Operations: Batch operations (e.g., dot product,sum)

In [5]:
# Sum of large arrays
import time
a = np.arange(1e6)
b = list(range(int(1e6)))

start = time.time(); sum(a); print("NumPy:", time.time() - start)
start = time.time(); sum(b); print("List:", time.time() - start)

NumPy: 0.10098600387573242
List: 0.00826406478881836


7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and
output.

ANSWER : vstack() vs hstack()

*vstack() (vertical): Stack arrays row-wise (increases row count).

*hstack() (horizontal): Stack arrays column-wise (increases column count).

In [7]:
a = np.array([1, 2])
b = np.array([3, 4])

np.vstack((a, b))


array([[1, 2],
       [3, 4]])

In [8]:
a = np.array([1, 2])
b = np.array([3, 4])

np.hstack((a, b))

array([1, 2, 3, 4])

8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various
array dimensions.

ANSWER : fliplr() vs flipud()

*fliplr(): Flips array left to right (columns).

*flipud(): Flips array upside down (rows).

In [9]:
a = np.array([[1, 2], [3, 4]])

np.fliplr(a)


array([[2, 1],
       [4, 3]])

In [10]:
a = np.array([[1, 2], [3, 4]])
np.flipud(a)

array([[3, 4],
       [1, 2]])

9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

ANSWER :Functionality of array_split()

*Purpose: Split arrays into sub-arrays. Unlike split(), it allows uneven splits.

In [11]:
a = np.array([1, 2, 3, 4, 5])
np.array_split(a, 3)

[array([1, 2]), array([3, 4]), array([5])]

10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array
operations?

ANSWER : Vectorization and Broadcasting

*Vectorization: Performing operations on entire arrays without explicit loops.

*Increases performance by leveraging low-level optimizations.

In [ ]:
a + b  # Element-wise addition, vectorized

*Broadcasting: Automatically expands arrays of different shapes to enable operations.

In [12]:
a = np.array([[1], [2], [3]])
b = np.array([10, 20])
a + b

array([[11, 21],
       [12, 22],
       [13, 23]])

**PRACTICAL QUESTIONS**

1. Create 3x3 Array with Random Integers & Transpose

In [13]:
import numpy as np

arr = np.random.randint(1, 101, (3, 3))
print("Original array:\n", arr)

transposed = arr.T  # or np.transpose(arr)
print("Transposed array:\n", transposed)

Original array:
 [[71 55 29]
 [57  7 75]
 [79 45 99]]
Transposed array:
 [[71 57 79]
 [55  7 45]
 [29 75 99]]


2. 1D Array → 2x5 → 5x2

In [14]:
arr1d = np.arange(10)
arr2x5 = arr1d.reshape(2, 5)
arr5x2 = arr2x5.reshape(5, 2)
print("2x5:\n", arr2x5)
print("5x2:\n", arr5x2)

2x5:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
5x2:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


3. 4x4 Float Array with Zero Border

In [15]:
arr4x4 = np.random.rand(4, 4)
bordered = np.pad(arr4x4, pad_width=1, mode='constant', constant_values=0)
print("6x6 with border:\n", bordered)

6x6 with border:
 [[0.         0.         0.         0.         0.         0.        ]
 [0.         0.50326625 0.19087876 0.79231126 0.76815411 0.        ]
 [0.         0.99665738 0.32503148 0.57272308 0.35670178 0.        ]
 [0.         0.81628728 0.42489022 0.27160196 0.72884003 0.        ]
 [0.         0.3361686  0.11754483 0.64740365 0.06084047 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


4.  Array of Integers from 10 to 60 (Step 5)

In [16]:
step_arr = np.arange(10, 61, 5)
print(step_arr)

[10 15 20 25 30 35 40 45 50 55 60]


5. Case Transformations on String Array

In [17]:
arr = np.array(['python', 'numpy', 'pandas'])

upper = np.char.upper(arr)
lower = np.char.lower(arr)
title = np.char.title(arr)

print("Upper:", upper)
print("Lower:", lower)
print("Title:", title)

Upper: ['PYTHON' 'NUMPY' 'PANDAS']
Lower: ['python' 'numpy' 'pandas']
Title: ['Python' 'Numpy' 'Pandas']


6. Insert Space Between Each Character

In [18]:
words = np.array(['data', 'array', 'python'])
spaced = np.char.join(' ', words)
print(spaced)


['d a t a' 'a r r a y' 'p y t h o n']


7. Element-wise Operations on 2D Arrays

In [19]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print("Addition:\n", a + b)
print("Subtraction:\n", a - b)
print("Multiplication:\n", a * b)
print("Division:\n", a / b)

Addition:
 [[ 6  8]
 [10 12]]
Subtraction:
 [[-4 -4]
 [-4 -4]]
Multiplication:
 [[ 5 12]
 [21 32]]
Division:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


8.  5x5 Identity Matrix & Extract Diagonal

In [20]:
identity = np.eye(5)
diagonal = np.diag(identity)
print("Diagonal elements:", diagonal)

Diagonal elements: [1. 1. 1. 1. 1.]


9. Find Prime Numbers in Random Integer Array

In [21]:
def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(n**0.5)+1):
        if n % i == 0:
            return False
    return True

rand_arr = np.random.randint(0, 1001, 100)
primes = rand_arr[np.vectorize(is_prime)(rand_arr)]
print("Prime numbers:", primes)


Prime numbers: [761 953 773 313 911 907 349 163 743 787 307 271 373 439 433 401 827]


10. Daily Temperatures → Weekly Averages
python
Copy code


In [22]:
# Simulate daily temperatures for a 30-day month
temps = np.random.uniform(15, 35, 30)  # e.g., 15–35°C

# Reshape into weeks (6 weeks of 5 days each or 4 full + 2 extra days)
weekly = temps[:28].reshape(4, 7)
weekly_averages = np.mean(weekly, axis=1)

print("Weekly averages:", weekly_averages)


Weekly averages: [23.80176607 24.91072141 23.93146778 25.64205235]
